server:
  port : 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskflow_v1
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true